site_name: Supervised and Unsupervised Machine Learning
site_description: Supervised and Unsupervised Learning section of the Algorithms in Machine Learning class at ISAE-Supaero
site_url: https://supaerodatascience.github.io/
site_dir: site
strict: false
use_directory_urls: false

theme:
  name: 'material'
  palette:
    primary: light blue
    accent: light blue
  logo: 'https://raw.githubusercontent.com/SupaeroDataScience/machine-learning/main/src/favicon.ico'
  favicon: 'https://raw.githubusercontent.com/SupaeroDataScience/machine-learning/main/src/favicon.ico'
  features:
    - toc.autohide

repo_name: SupaeroDataScience/machine-learning
repo_url: https://github.com/SupaeroDataScience/machine-learning

nav:
- Home: index.md
- Introduction:
  - Introduction to ML: intro.md
  - A quick tour of Unsupervised Learning: unsup.md
  - The importance of data preprocessing: preproc.md
- A geometrical approach to ML:
  - SVMs, the bias-variance tradeoff and a bit of kernel theory: svm.md
  - An application of SVMs to multi-label classification: mlc.md
- A probabilistic approach to ML:
  - Naive Bayes Classification: nbc.md
  - Gaussian Processes: gp.md
  - Surrogate Modeling and Bayesian Optimization: surrog.md
- Mimicking the human brain, the connectionist approach:
  - Neural networks: nn.md
- Commitee-based methods:
  - Decision trees: trees.md
  - Boosting: boost.md
  - Gradient Boosting and XGBoost: xgboost.md
  - Bagging: bagging.md
  - Random Forests: rf.md
  - Anomaly Detection: anomaly.md
- Perspectives:
  - Explainability in ML: xai.md

markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- toc:
    permalink: ðŸ”—
- admonition
- codehilite
- extra
- attr_list
- pymdownx.details
- pymdownx.superfences

plugins:
- search
